### ISSUE TITLE
Don't set the type to "contacts" or you will endlessly crash Discord

### ISSUE THREAD

**Issue by kast1450** [ryanrohypnol/Discord-Custom-Connections#1]
`{"provider_id": ["Value must be one of ('battlenet', 'contacts', 'skype', 'leagueoflegends')."]}`

Don't set it to contacts or you will constantly crash and are unable to remove the connection.

**Comment by ryanrohypnol** [comment]
While in Discord press **CTRL+SHIFT+i** 
Press the **Network** tab
Go to your **settings/connections**
Press **connections**
Use the same ID in a **DELETE** request

That should fix the client side crash, let me know if you have any trouble!

**Comment by ryanrohypnol** [comment]
> `{"provider_id": ["Value must be one of ('battlenet', 'contacts', 'skype', 'leagueoflegends')."]}`
> 
> Don't set it to contacts or you will constantly crash and are unable to remove the connection.

While in Discord press **CTRL+SHIFT+i** 
Press the **Network** tab
Go to your **settings/connections**
Press **connections**
Use the same ID in a **DELETE** request

That should fix the client side crash, let me know if you have any trouble!

**Comment by kast1450** [comment]
Yeah, thanks. Changing it to a DELETE instead of a PUT request worked.
I wonder why "contacts" makes it crash when it says it's usable. Hmmm.

**Comment by ryanrohypnol** [comment]
It used to crash remotely as well, Discord patched it see below.

[](https://github.com/ryanrohypnol/Discord-Crash)
