### ISSUE TITLE
{"provider_id": ["Value must be one of ('contacts',)."]}

### ISSUE THREAD

**Issue by theroney** [ryanrohypnol/Discord-Custom-Connections#10]
{"provider_id": ["Value must be one of ('contacts',)."]}

**Comment by ghost** [comment]
He already told the other one people that asked this question.
Discord patched it!

The paradox is if you do publish the wrong people get it in the hand and then bullshit got created.

X Light

**Comment by ghost** [comment]
If you need help: LightJavaCode#4459.
X Light

**Comment by akayiz** [comment]
So there isn't any fix for it??
