### ISSUE TITLE
Value must be one of ()

### ISSUE THREAD

**Issue by xorpt** [ryanrohypnol/Discord-Custom-Connections#2]
`{"provider_id": ["Value must be one of ()."]}`
is what is returned after the PUT request

my only guess is that they patched it

**Comment by ryanrohypnol** [comment]
> `{"provider_id": ["Value must be one of ()."]}`
> is what is returned after the PUT request
> 
> my only guess is that they patched it

Unfortunately, I think they patched it as well. I’ll keep looking for a new method. Check back, can’t make any promises :-/

**Comment by ryanrohypnol** [comment]
@xorpt fixed
